controller:
  ingressClassResource:
    name: external-nginx
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
  # Required for ACME
  watchIngressWithoutClass: true
  extraArgs:
    ingress-class: external-nginx
tcp:
  22: "gitlab/gitlab-gitlab-shell:22"
  5000: "sonatype/nexus3:3.61.0:5000"
